library(shiny)
library(ggplot2)
all_ages <- read.csv("all-ages.csv")

ui <- fluidPage(
  
  # sliderInput(inputId = "num", 
  #             label = "Choose a number", 
  #             value = 25, min = 1, max = 100),
  # plotOutput("hist")
  titlePanel("College Major Web App"),
  tags$div(class="header", checked=NA,
           tags$p("This web app shows boxplots displaying salaries for various college major categories, stratified by salary quartiles."),
           tags$p("For example, the engineering boxplot is generated by taking the 'nth' quartile salary for areospace engineering, chemical engineering, electrical engineering, etc."),
           tags$p("You can change which quartile the datapoints are being taken from to compute the box plots using the selector tool below."),
           tags$p("Note that these plots are displaying the salaries of people who majored in these fields, not the salaries being offered in those fields. For example, the salary of physics graduate
                  working as a computer scientist would be used in computing the physical sciences boxplot, not the computers and mathematics boxplot."),
           tags$p("You can find the source data for this project from "),
           tags$a(href="https://github.com/fivethirtyeight/data/tree/master/college-majors", "here!")
  ),
  selectInput(inputId = "sal_quart", label = "Salary Quartile", 
              choices = c("25th Percentile"= "P25th", "50th Percentile" = "Median", "75th Percentile" = "P75th")),
  plotOutput("boxPlot")  
)


server <- function(input, output) {
  output$boxPlot <- renderPlot({
    
    user_input <- input$sal_quart

    g <- ggplot(all_ages, (aes(all_ages$Major_category, 
                               eval(parse(text = paste("all_ages$", user_input, sep = "")))
                               ))) + ylim(0, 150000)
    g <- g + geom_boxplot(aes(color = all_ages$Major_category))
    g <- g + theme_bw() +theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())
    g <- g + scale_color_discrete("Major Category")
    g <- g + labs(x = "Major Category", y = "Salary") 
    g
  })
}

shinyApp(ui = ui, server = server)